package com.xrosstools.xflow;

import java.util.List;

public interface TaskActivity {
	/**
	 * Create tasks that need to be handled
	 * @param context the execution context
	 * @return id that differentiates tasks created each time  
	 */
	List<Task> create(XflowContext context);

	/**
	 * Submit a task
	 * @param context the execution context
	 * @param tasks all the tasks that are generated by create method
	 * @param task current task that user submitted
	 * @return true if activity completed
	 */
	boolean submit(XflowContext context, List<Task> tasks, Task task);
}
